In [2]:
import numpy as np

In [14]:
#Exercício 5.1

a = np.arange(12).reshape(3,4)

print(a)

print(a[1,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7


In [33]:
#Exercício 5.2 e 5.3

#Extrair uma submatriz de uma matriz original 

matriz = np.arange(100).reshape(10,10)

c1 = matriz[:5,:5]
c2 = matriz[5:,:5]
c3 = matriz[:5,5:]
c4 = matriz[5:,5:]
print(c1)
print(c2)
print(c3)
print(c4)

novaMatrizA = np.concatenate((c3,c4), axis = 0)
novaMatrizB = np.concatenate((c2,c1), axis = 0)
novaMatrizC = np.concatenate((novaMatrizA,novaMatrizB), axis = 1)

print(novaMatrizC)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]
[[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]
 [95 96 97 98 99]]
[[ 5  6  7  8  9 50 51 52 53 54]
 [15 16 17 18 19 60 61 62 63 64]
 [25 26 27 28 29 70 71 72 73 74]
 [35 36 37 38 39 80 81 82 83 84]
 [45 46 47 48 49 90 91 92 93 94]
 [55 56 57 58 59  0  1  2  3  4]
 [65 66 67 68 69 10 11 12 13 14]
 [75 76 77 78 79 20 21 22 23 24]
 [85 86 87 88 89 30 31 32 33 34]
 [95 96 97 98 99 40 41 42 43 44]]


In [5]:
#Exercício 5.4

#Soma de matrizes de maneira simples

A = np.random.randint(0,10,(3,3))
B = np.random.randint(0,10,(3,3))

resultado = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        resultado[i,j] = A[i,j] + B[i,j]

print(resultado)


[[ 9.  9.  6.]
 [13.  9. 10.]
 [ 2. 11. 10.]]


In [6]:
#Exercício 5.5  - Distibuitividade

A = np.random.rand(3,4)
B = np.random.rand(3,4)
sigma = np.random.rand()

expr1 = sigma*(A+B)
expr2 = sigma*A + sigma*B
expr3 = A*sigma + B*sigma

print(np.allclose(expr1, expr2))
print(np.allclose(expr1, expr3))

True
True


In [7]:
#Exercício 5.6 - Multiplicação de matrizes

A = np.random.randint(0,10,(2,3))
B = np.random.randint(0,10,(3,2))

resultado = np.zeros((2,2))

for i in range(2):
    for j in range(2):
        for k in range(3):
            resultado[i,j] += A[i,k]*B[k,j]

print("Manual:")
print(resultado)

print("NumPy:")
print(A @ B)

Manual:
[[ 8. 64.]
 [77. 95.]]
NumPy:
[[ 8 64]
 [77 95]]


In [10]:
#Exercício 5.7 - Regra LIVE EVIL

L = np.random.rand(2,6)
I = np.random.rand(6,3)
V = np.random.rand(3,5)
E = np.random.rand(5,2)

prod = L @ I @ V @ E

# passo 2
res1 = prod.T

# passo 3 (errado)
#res2 = L.T @ I.T @ V.T @ E.T

# passo 4 (correto)
res3 = E.T @ V.T @ I.T @ L.T

#print(np.allclose(res1, res2)) # False
print(np.allclose(res1, res3)) # True

True


In [11]:
#Exercício 5.8 - Matriz Assimétrica

def eh_simetrica(A):
    return np.allclose(A, A.T)

A = np.array([[1,2,3],
              [2,5,6],
              [3,6,9]])

print(eh_simetrica(A))

True


In [12]:
#Exercício 5.9 - Criar matriz simétrica

A = np.random.rand(3,3)

simetrica = (A + A.T)/2

print(eh_simetrica(simetrica))

True


In [ ]:
#Exercício 5.10 - Matriz Vetor

A = np.random.rand(3,3)
s = np.random.rand(3)

resultado = A @ s

print(resultado)

[0.50147387 0.88495271 0.74743808]


In [14]:
#Exercicio 5.11 - Matriz diagonal

ones = np.ones((4,4))

D = np.diag([1,4,9,16])
D_sqrt = np.diag([1,2,3,4])

print("Pré:")
print(D @ ones)

print("Pós:")
print(ones @ D)

print("Ambos:")
print(D_sqrt @ ones @ D_sqrt)

Pré:
[[ 1.  1.  1.  1.]
 [ 4.  4.  4.  4.]
 [ 9.  9.  9.  9.]
 [16. 16. 16. 16.]]
Pós:
[[ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]]
Ambos:
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


In [15]:
#Exercicio 5.12 - Diagonal

D1 = np.diag([1,2,3])
D2 = np.diag([4,5,6])

mult_matriz = D1 @ D2
hadamard = D1 * D2

print(mult_matriz)
print(hadamard)

[[ 4  0  0]
 [ 0 10  0]
 [ 0  0 18]]
[[ 4  0  0]
 [ 0 10  0]
 [ 0  0 18]]
