In [6]:
import numpy as np
import scipy.linalg as sla

In [ ]:
#Exemplo 1.1

a = np.array([[1,1,1], [4,2,2],[2,1,-1]])
ex = np.array([["x"],["y"],["z"]])
b = np.array([[1],[2],[0]])

In [ ]:
#Concatenação por colunas

#Apenas acontece quando temos a mesma quantidade de linhas e colunas
a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
#Exemplo 2.1

A = np.array([[2,3,5],[1,-1,10],[-1,1,-1]])

b = np.array([10,20,5])

np.linalg.matrix_rank(A)
np.linalg.matrix_rank(np.c_[A, b])
A.shape[1]

3

In [32]:
#Exercicio 1.1
#A)

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,1,1])

print(np.linalg.matrix_rank(a)) # = 2
print(np.linalg.matrix_rank(np.c_[a, b])) # = 2
print(a.shape[1]) # = 3

#SIATEMA INDETERMINADO


2
2
3


In [33]:
#B)

j = np.array([[2,3],[-4,-6]])
k = np.array([10,-10])

print(np.linalg.matrix_rank(j))
print(np.linalg.matrix_rank(np.c_[j,k])) 
print(j.shape[1]) 
#SISTEMA IMPOSSIVEL

1
2
2


In [ ]:
#Algoritmo 1.1

matriz = np.array([[1,0,0,0],
                   [0,2,6,0],
                   [0,0,3,0],
                   [0,0,0,4]])

b = np.array([[6,10,8,9]])

x = np.zeros(4)

k,j = matriz.shape

for i in range((4)):
    x[i] = b[0][i] / matriz[i][i]


print(x)
#for i in range()

[6.         5.         2.66666667 2.25      ]


In [ ]:
#Mesma Solução anterior com a função numpy
def sist_lin_diagonal(A,b): 
    return b/A.diagonal()
print(sist_lin_diagonal(matriz,b))


[[6.         5.         2.66666667 2.25      ]]


In [68]:
#Exemplo 3.1

A = np.diag([1,4,2])
b = np.array([4, 2, 2])

print(sist_lin_diagonal(A,b))

[4.  0.5 1. ]


In [71]:
#Algoritmo 1.2

A = np.diag([1,4,2])
b = np.array([4, 2, 2])

lista = sist_lin_diagonal(A,b)

j,k = A.shape

n = len(b)
maximo = max(lista)

for i in range(n-2, -1, -1):
    soma = 0

    for j in range(i+1, n):
        soma += A[i][j] * x[j]

    x[i] = (b[i] - soma) / A[i][i]


print(x)

[4.         0.5        2.66666667 2.25      ]


In [70]:
def sist_lin_tri_sup(A,b):

    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

print(sist_lin_tri_sup(A,b))

[4.  0.5 1. ]


In [74]:
#Exemplo 3.2

A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])

b = np.array([-10,-1,3,2])

x = sist_lin_tri_sup(A,b)

print(x)

print(A.dot(x))

[ 1. -1.  2.  1.]
[-10.  -1.   3.   2.]


In [ ]:
#Algoritmo 1.3

A = np.array([
    [2, 0, 0],
    [3, 4, 0],
    [1, 5, 6]
], dtype=float)

b = np.array([4, 11, 29], dtype=float)

n = A.shape[0]

x = np.zeros(n)

x[0] = b[0] / A[0][0]

for i in range(1, n):

    soma = 0

    for j in range(i):
        soma += A[i][j] * x[j]

    x[i] = (b[i] - soma) / A[i][i]

print("Vetor solução:")
print(x)

Vetor solução:
[2.         1.25       3.45833333]


In [77]:
def sist_lin_tri_inf(A,b):

    n = len(b)
    x = np.empty(n)
    x[0] = b[0]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

print(sist_lin_tri_inf(A,b))

[2.         1.25       3.45833333]


In [79]:
#Exemplo 3.3

A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])

b = np.array([4,2,4,2])

x = sist_lin_tri_inf(A,b)

print(x)
A.dot(x)


[ 1.33333333 -0.66666667  2.66666667 -1.33333333]


array([4., 2., 4., 2.])

In [81]:
#Exemplo 3.4

A1 = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])

b1 = np.array([-10,-1,3,2])

print(sla.solve_triangular(A1,b1, lower=False))

A2 = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])

b2 = np.array([4,2,4,2])

print(sla.solve_triangular(A2,b2, lower=True))


[ 1. -1.  2.  1.]
[ 1.33333333 -0.66666667  2.66666667 -1.33333333]


In [ ]:
#Exercício 1.3

def sist_lin_tri_inf(A, b):
    n = len(b)
    x = np.zeros(n)
    
    for i in range(n):
        soma = np.dot(A[i, :i], x[:i])
        x[i] = (b[i] - soma) / A[i, i]
        
    return x

A2 = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b2 = np.array([4,2,4,2])

resultado = sist_lin_tri_inf(A2, b2)
print(f"Resultado explícito: {resultado}")

Resultado explícito: [ 1.33333333 -0.66666667  2.66666667 -1.33333333]


In [83]:
#Exercicio 1.4

def resolver_sistema_trivial(A, b):
    # Garantir que são arrays do numpy
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    
    is_upper = np.allclose(A, np.triu(A))
    is_lower = np.allclose(A, np.tril(A))
    
    if is_upper and is_lower:
        print("Tipo identificado: Matriz Diagonal")
        # x = b_i / A_ii
        return b / np.diag(A)
        
    elif is_upper:
        print("Tipo identificado: Triangular Superior (Retro-substituição)")
        x = np.zeros(n)
        for i in range(n - 1, -1, -1):
            soma = np.dot(A[i, i+1:], x[i+1:])
            x[i] = (b[i] - soma) / A[i, i]
        return x
        
    elif is_lower:
        print("Tipo identificado: Triangular Inferior (Substituição Progressiva)")
        x = np.zeros(n)
        for i in range(n):
            soma = np.dot(A[i, :i], x[:i])
            x[i] = (b[i] - soma) / A[i, i]
        return x
    
    else:
        raise ValueError("A matriz não é diagonal, triangular superior ou inferior.")

# --- Teste com os dados do Exemplo 3.4 ---

A_sup = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b_sup = np.array([-10, -1, 3, 2])

A_inf = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b_inf = np.array([4, 2, 4, 2])

print(f"Solução Superior: {resolver_sistema_trivial(A_sup, b_sup)}")
print(f"Solução Inferior: {resolver_sistema_trivial(A_inf, b_inf)}")

Tipo identificado: Triangular Superior (Retro-substituição)
Solução Superior: [ 1. -1.  2.  1.]
Tipo identificado: Triangular Inferior (Substituição Progressiva)
Solução Inferior: [ 1.33333333 -0.66666667  2.66666667 -1.33333333]
