# 📘 Aula 1 — Indexing and Slicing Arrays

---

## 🔹 Indexação em Arrays 1D

```python
array = np.array([2, 4, 6, 8, 10])
array[3]


🔹 Indexação em Arrays 2D
Elemento específico

In [1]:
import numpy as np

In [2]:
sudoku_game = np.array([
    [0, 0, 4, 3, 0, 0, 2, 0, 9],
    [0, 0, 5, 0, 0, 9, 0, 0, 1],
    [0, 7, 0, 0, 6, 0, 0, 4, 3],
    [0, 0, 6, 0, 0, 2, 0, 8, 7],
    [1, 9, 0, 0, 0, 7, 4, 0, 0],
    [0, 5, 0, 0, 8, 3, 0, 0, 0],
    [6, 0, 0, 0, 0, 0, 1, 0, 5],
    [0, 0, 3, 5, 0, 8, 6, 9, 0],
    [0, 4, 2, 9, 1, 0, 3, 0, 0]
])

In [3]:
sudoku_game[2, 4]


np.int64(6)

Formato geral:

array[linha,coluna]

Linha inteira

In [4]:
sudoku_game[0]


array([0, 0, 4, 3, 0, 0, 2, 0, 9])

Coluna inteira


In [5]:
sudoku_game[:, 3]


array([3, 0, 0, 0, 0, 0, 0, 5, 9])

📘 Slicing (Fatiamento)


🔹 Slicing 1D

In [7]:
array = [1,2,3,4,5,6,7]

In [8]:
array[2:4]


[3, 4]

Formato geral:


array[inicio:fim]

🔹 Slicing 2D

In [9]:
sudoku_game[3:6, 3:6]


array([[0, 0, 2],
       [0, 0, 7],
       [0, 8, 3]])

Formato:

array[linhas,colunas]

🔹 Slicing com Step

In [10]:
sudoku_game[3:6:2, 3:6:2]


array([[0, 2],
       [0, 3]])

Formato:

array[inicio:fim:passo]

📘 Ordenação (Sorting)

🔹 Ordenação padrão

In [11]:
np.sort(sudoku_game)


array([[0, 0, 0, 0, 0, 2, 3, 4, 9],
       [0, 0, 0, 0, 0, 0, 1, 5, 9],
       [0, 0, 0, 0, 0, 3, 4, 6, 7],
       [0, 0, 0, 0, 0, 2, 6, 7, 8],
       [0, 0, 0, 0, 0, 1, 4, 7, 9],
       [0, 0, 0, 0, 0, 0, 3, 5, 8],
       [0, 0, 0, 0, 0, 0, 1, 5, 6],
       [0, 0, 0, 0, 3, 5, 6, 8, 9],
       [0, 0, 0, 0, 1, 2, 3, 4, 9]])

🔹 Ordenando por eixo

In [12]:
np.sort(sudoku_game, axis=0)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 2, 1, 0, 1],
       [0, 4, 3, 0, 0, 3, 2, 0, 3],
       [0, 5, 4, 3, 1, 7, 3, 4, 5],
       [1, 7, 5, 5, 6, 8, 4, 8, 7],
       [6, 9, 6, 9, 8, 9, 6, 9, 9]])

📌 Conceito importante:

axis=0 → ordena por colunas

axis=1 → ordena por linhas

# Aula 2 - 📘 Filtering Arrays

🔹 Duas formas de filtrar:

Boolean Masks + Fancy Indexing

np.where()

📘 Boolean Masks


In [13]:
one_to_five = np.arange(1, 6)
mask = one_to_five % 2 == 0


Mask gerada: 

[False,True,False,True,False]

🔹 Fancy Indexing (1D)

In [14]:
one_to_five[mask]


array([2, 4])

Resultado:

[2,4]

🔹 Fancy Indexing (2D)

In [21]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
print(classroom_ids_and_sizes)
classroom_ids_and_sizes[:, 0][classroom_ids_and_sizes[:, 1] % 2 == 0]


[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]


array([1, 4])

📘 np.where()

🔹 Retorna índices

In [22]:
np.where(classroom_ids_and_sizes[:, 1] % 2 == 0)


(array([0, 3]),)

Retorna:

(array([0,3]),)

🔹 Recuperando linhas e colunas

In [23]:
row_ind, column_ind = np.where(sudoku_game == 0)



📌 np.where() retorna uma tupla de índices.


🔹 Find and Replace

In [24]:
np.where(sudoku_game == 0, "", sudoku_game)



array([['', '', '4', '3', '', '', '2', '', '9'],
       ['', '', '5', '', '', '9', '', '', '1'],
       ['', '7', '', '', '6', '', '', '4', '3'],
       ['', '', '6', '', '', '2', '', '8', '7'],
       ['1', '9', '', '', '', '7', '4', '', ''],
       ['', '5', '', '', '8', '3', '', '', ''],
       ['6', '', '', '', '', '', '1', '', '5'],
       ['', '', '3', '5', '', '8', '6', '9', ''],
       ['', '4', '2', '9', '1', '', '3', '', '']], dtype='<U21')

Formato geral:

np.where(condicao,valor_se_verdadeiro,valor_se_falso)

# Aula 3 - Adicionando e Removendo Dados

🔹 Concatenando Linhas

In [27]:
array1= np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
array2= np.array([[1,"James"], [1,"George"], [3,"Amy"],[3,"Meehir"]])
np.concatenate((array1, array2))


array([['1', '22'],
       ['2', '21'],
       ['3', '27'],
       ['4', '26'],
       ['1', 'James'],
       ['1', 'George'],
       ['3', 'Amy'],
       ['3', 'Meehir']], dtype='<U21')

Por padrão:

axis=0


🔹 Concatenando Colunas

In [28]:
np.concatenate((array1, array2), axis=1)


array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U21')

📘 Compatibilidade de Shape

Se um array tem formato:

(
𝑚
,
𝑛
)
(m,n)

Para concatenar:

Mesmo número de colunas → axis=0

Mesmo número de linhas → axis=1

🔹 Criando compatibilidade com reshape

In [33]:
array1.reshape((8,1))
array2.reshape((8,1))


array([['1'],
       ['James'],
       ['1'],
       ['George'],
       ['3'],
       ['Amy'],
       ['3'],
       ['Meehir']], dtype='<U21')

📘 Removendo Dados

🔹 Remover linha

In [35]:
np.delete(array1, 1, axis=0)


array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

🔹 Remover coluna

In [36]:
np.delete(array1, 1, axis=1)


array([[1],
       [2],
       [3],
       [4]])

🔹 Remover sem especificar eixo

In [37]:
np.delete(array1, 1)


array([ 1,  2, 21,  3, 27,  4, 26])

⚠ Sem eixo → o array é achatado (flatten).