# Aula 1 - 🔢 Métodos de Agregação

Principais métodos para resumir dados:

.sum() → Soma dos elementos

.min() → Valor mínimo

.max() → Valor máximo

.mean() → Média dos valores

.cumsum() → Soma acumulada

📌 Argumento axis

Define a direção da agregação:

axis=0 → agrega por colunas

axis=1 → agrega por linhas


In [1]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])

array.sum(axis=0)  # Soma por coluna
array.sum(axis=1)  # Soma por linha


array([ 6, 15])

📌 Argumento keepdims

Mantém a dimensionalidade original do array:

In [2]:
array.sum(axis=1, keepdims=True)


array([[ 6],
       [15]])

# Aula 2 - ⚡ Operações Vetorizadas

NumPy permite realizar operações diretamente sobre arrays sem usar loops.

➕ Operações com escalar

In [3]:
array + 3
array * 3


array([[ 3,  6,  9],
       [12, 15, 18]])

➕ Operações entre arrays

In [12]:
array_a = np.array([1,2,3,4,5,6,7,8])
array_b = np.array([9,10,11,12,13,14,15,16])

print(array_a + array_b)
print(array_a * 3)


[10 12 14 16 18 20 22 24]
[ 3  6  9 12 15 18 21 24]


🔍 Comparações Vetorizadas

Operações booleanas também funcionam diretamente:

In [13]:
array > 2


array([[False, False,  True],
       [ True,  True,  True]])

🧠 Vetorizando funções Python

In [22]:
array_d = np.array(["NumPy", "is", "awesome"])

vectorized_len = np.vectorize(len)
vectorized_len(array_d) > 2
#print(array_d) 


array([ True, False,  True])

# Aula 03 - 📡 Broadcasting

Broadcasting permite operações entre arrays de tamanhos diferentes, seguindo regras específicas.

📏 Regras de Compatibilidade

NumPy compara dimensões da direita para a esquerda.

Duas dimensões são compatíveis quando:

São iguais, ou

Uma delas é 1

✅ Exemplos Compatíveis

(10, 5) e (10, 1)

(10, 5) e (5,)

❌ Exemplos Incompatíveis

(10, 5) e (5, 10)

(10, 5) e (10,)

🔄 Broadcasting de Linhas

In [25]:
array = np.arange(10).reshape((2, 5))
print(array)
array + np.array([0, 1, 2, 3, 4])

# (2,5) e (1,5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

🔄 Broadcasting de Colunas

In [ ]:
array + np.array([0, 1]).reshape((2, 1))

# (2,5) e (2,1)

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])