# 📘 Aula 1 — Introdução ao NumPy

## 🔹 O que é NumPy?

NumPy é uma biblioteca fundamental para computação numérica em Python.  
Ela permite trabalhar com **arrays multidimensionais** de forma eficiente.

### ✅ Principais vantagens:
- Melhor uso de memória
- Operações matemáticas vetorizadas
- Alto desempenho
- Base para bibliotecas como Pandas, SciPy e Scikit-learn

---

## 🔹 Importando o NumPy

```python
import numpy as np


# 🔹 Criando Arrays

In [7]:
import numpy as np


📌 Array 1D

In [ ]:
python_list = [3, 2, 5, 8]
array = np.array(python_list)

📌 Array 2D (Matriz)

In [9]:
python_list = [[3, 2, 5],
               [9, 7, 1],
               [4, 3, 6]]

array_2d = np.array(python_list)


# Listas vs Arrays

🐍 Lista Python

Pode conter diferentes tipos de dados

🔢 Array NumPy

Contém apenas um tipo de dado

Usa menos memória

Mais rápido para cálculos matemáticos



🔹 Criando Arrays do Zero
np.zeros()

In [10]:
np.zeros((5,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

np.random.random()

In [11]:
np.random.random((2,4))


array([[0.20309245, 0.47651606, 0.09027351, 0.23062574],
       [0.93241776, 0.7569353 , 0.71158044, 0.69719149]])

np.arange()

In [12]:
np.arange(4)
np.arange(-3,4)
np.arange(-3,4,3)


array([-3,  0,  3])

# 📘 Aula 2 — Dimensionalidade de Arrays
🔹 Dimensões

1D → Vetor

2D → Matriz

3D ou mais → Tensor

🔹 Shape

O atributo .shape mostra as dimensões do array.

In [19]:
array = np.zeros((3,5))
print(array)
array.shape


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(3, 5)

🔹 Flatten

Transforma um array em 1D:

In [18]:
val = array.flatten()
print(val)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


🔹 Reshape

Altera o formato mantendo o número de elementos.

In [21]:
array.reshape((5,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 📘 Aula 3 — Tipos de Dados no NumPy
🔹 Tipos NumPy

np.int32

np.int64

np.float32

np.float64

🔹 dtype

Mostra o tipo do array:

In [22]:
array.dtype


dtype('float64')

🔹 Definindo tipo manualmente

In [23]:
np.array([1.2, 5.7], dtype=np.float32)


array([1.2, 5.7], dtype=float32)

🔹 Conversão de tipo

In [24]:
array.astype(np.int32)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

🔹 Type Coercion (Conversão automática)

Quando misturamos tipos:

bool + int → vira int

int + float → vira float

misturar com string → tudo vira string

In [25]:
np.array([True, "Boop", 42])


array(['True', 'Boop', '42'], dtype='<U21')